[build]
  # No build command needed for static files
  command = ""
  
  # Publish directory is the root
  publish = "."
  
  # No functions directory needed
  functions = ""

[build.environment]
  # Use Node.js for static site generation (even though we don't need it)
  NODE_VERSION = "18"
  # Disable Python to prevent pip installs
  PYTHON_VERSION = ""

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 200

# Headers for CORS (if needed)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
